timeout: 1800s

steps:
# Set up builder for muti-arch builds.
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--privileged', 'linuxkit/binfmt:v0.7']
  id: 'initialize-qemu'
- name: 'gcr.io/cloud-builders/docker'
  args: ['buildx', 'create', '--use', '--platform', '${_DOCKER_BUILDX_PLATFORMS}']
  id: 'create-builder'


# First, build kaniko
- name: "gcr.io/cloud-builders/docker"
  args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', "-f", "deploy/Dockerfile",
         "-t", "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:$TAG_NAME",
         "-t", "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:latest", "--push", "."]

# Then executor:slim image
- name: "gcr.io/cloud-builders/docker"
  args: ['buildx', 'build', '--platform', '$_DOCKER_BUILDX_PLATFORMS', "-f", "deploy/Dockerfile_slim",
         "-t", "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:$TAG_NAME-slim",
         "-t", "gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:slim", "--push", "."]




# Sign the images

- name: $_COSIGN_IMAGE
  args: ['sign', '-kms', '$_KMS', 'gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:$TAG_NAME']
- name: $_COSIGN_IMAGE
  args: ['sign', '-kms', '$_KMS', 'gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:latest']
- name: $_COSIGN_IMAGE
  args: ['sign', '-kms', '$_KMS', 'gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:$TAG_NAME-slim']
- name: $_COSIGN_IMAGE
  args: ['sign', '-kms', '$_KMS', 'gcr.io/$PROJECT_ID/${_EXECUTOR_IMAGE_NAME}:slim']

options:
  env:
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'

substitutions:
  _EXECUTOR_IMAGE_NAME: executor
  _DOCKER_BUILDX_PLATFORMS: 'linux/arm64'
  _KMS: gcpkms://projects/priya-wadhwa/locations/global/keyRings/cosign/cryptoKeys/cosign
  _COSIGN_IMAGE: gcr.io/projectsigstore/cosign/ci/cosign@sha256:26959da00d822c407800451beeb706f4a7bc372bd2cd1145e0ed2d02e5999f1e
